services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/usr/src/app-server/src
    command: npm run dev

  client:
    build: ./client
    expose:
      - ${CLIENT_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_PORT: ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/usr/src/app-client/src
      - ./client/public:/usr/src/app-client/public
    links:
      - server
    command: npm run start
