services:
  server:
    image: bisol84/myapp-server:latest
    container_name: myapp-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - myapp-network

  client:
    image: bisol84/myapp-client:latest
    container_name: myapp-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - myapp-network
    depends_on:
      - server

networks:
  myapp-network:
    driver: bridge
